import { sans } from "@/styles/fonts";
import "../styles/globals.css";
import { Nav } from "@/components/shared";
import { getCurrentUser } from "@/lib/session";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { Providers } from "@/components/providers";

export const metadata = {
  title: "CodeSage.io",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className={sans.className}>
        <TailwindIndicator />
        <Providers>
          <div className="flex flex-col">
            <Nav user={user} />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
